language: node_js

services:
    - docker

deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t thetablestop/rancher-linode:$TRAVIS_BUILD_NUMBER .
    - docker push thetablestop/rancher-linode:$TRAVIS_BUILD_NUMBER
