apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: rancher-linode
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-apps-rancher-linode
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: apps
  name: rancher-linode
spec:
  rules:
  - host: rancher-linode.thetablestop.com
    http:
      paths:
      - backend:
          serviceName: rancher-linode
          servicePort: http
  tls:
  - hosts:
    - rancher-linode.thetablestop.com
    secretName: star-thetablestop-com
